### ISSUE TITLE
have gary look at

### ISSUE THREAD

**Issue by luxe** [UniLang/units_to_variable_suffix_converter#3]
@gheckman 
these are being used in f2si generation.  
Figured I'd get an extra pair of eyes to clean/re-organize them again.

**Comment by gheckman** [comment]
,{"revolutions / minute","rpm"}
Under speed. Suggest putting under angular velocity. (Suggest changing speed to velocity)

  ,{"pounds / minute","ppm"}
  ,{"pounds / hour","pph"}
Under force. Unsure where they should go. Perhaps flow rate.

  ,{"degrees / second","degps"}
Under angles. Suggest putting under angular velocity.

  ,{"coulomb per volt",""}
Suggest CpV for unit. Don't think this one is standard, so not sure what to do.

  //work
Suggest adding Newton meters "Nm"

**Comment by luxe** [comment]
changed
